### ISSUE TITLE
Problème d'inventaire

### ISSUE THREAD

**Issue by yppdr** [NinjaSourceV2/nCoreGTA#11]
Bonjour, 

Avec @Norfair00 nous avons eu un problème d'affichage de l'inventaire que nous avons "résolu" en modifiant `{ ['@username'] = player}` par `{ ['@username'] = license}` CF. le code :
 https://github.com/NinjaSourceV2/nCoreGTA/blob/c9884363afb31164b2c74ecb1cb52df902c2c73e/resources/%5BGTA_Resources%5D/nMenuPersonnel/server/server_inventaire.lua#L14 

Mais nous avons toujours un problème sur la soustraction des items de l'inventaire comme l'eau qui repop apres l'utilisation

**Comment by norfair00** [comment]
Le téléphone n'est pas détecté non plus même quand on l'a dans l'inventaire.

**Comment by norfair00** [comment]
J'ai fait la modification sur mon fork https://github.com/DebansCommunity/nCoreGTA/commit/49248317643708b6fea59c5f824d9d340edad7b6

Je taff que quelque autre modif

**Comment by norfair00** [comment]
Bon en bref ya plus de MAJ c'est ça ??

**Comment by yppdr** [comment]
Up ?

**Comment by norfair00** [comment]
> 
> 
> Up ?

Up !!!!

**Comment by SuperCoolNinja** [comment]
Désolé du retard, c'est fixé.
